feat: flameを使用したゲーム画面初期実装
rainbeek/isekai pull request #18
Opened 2023-06-21 14:56 UTC by hacker-takeda

## 概要
ゲーム画面の初期実装PR

 - マップは現状適当に作ったものを挿入
 - オレンジ色の四角をタップすることでスレッド画面に移動

2023-08-31 05:34 UTC, hacker-takeda commented on lib/data/usecase/message_use_case.dart
> +  // ignore: deprecated_member_use
streamはdeprecatedになったみたいでlintに怒られるが、一旦無視。

2023-08-31 06:42 UTC, hacker-takeda commented on .tool-versions
> +flutter 3.10.5-stable
戻しました！

2023-08-31 07:23 UTC, shotaIDE commented on lib/data/usecase/message_use_case.dart
> +  // ignore: deprecated_member_use
調査ありがとう！
これ `flutter_riverpod` とか他のライブラリが更新されてしまってるからだと思うので、このPRでは、以下を実施してもらって "ignore" は消してもらっていいですか？

1. `pubspec.yaml`と`pubspec.lock`、`ios/Podfile`、`ios/Podfile.lock`の変更を元に戻す
2. `dart pub add flame shared_preferences`を実行する

2023-09-02 08:12 UTC, hacker-takeda commented on lib/data/usecase/message_use_case.dart
> +  // ignore: deprecated_member_use
修正しますた！

2023-09-02 09:03 UTC, shotaIDE requested changes
`pubspec.yaml`のassetsの記述がなくなってて、実行できなくなってるので見直してもらえますか？🙏
<img width="1440" alt="image" src="https://github.com/rainbeek/isekai/assets/15522545/9faa04c6-4120-443c-8471-9435f89db311">

2023-09-02 15:30 UTC, hacker-takeda commented
失礼🙇‍♂️

[6441171](https://github.com/rainbeek/isekai/pull/18/commits/644117105cb4fa15a00b86b1d6f33ec656cc4901)

2023-09-03 01:31 UTC, shotaIDE approved these changes
LGTM！！

2023-09-03 01:32 UTC, merged